# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dev10\Desktop\Pokedex\ipokedex.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QProgressBar,
    QPushButton, QSizePolicy, QStackedWidget, QTabWidget,
    QTextBrowser, QVBoxLayout, QWidget)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pokedex(object):
    def setupUi(self, pokedex):
        pokedex.setObjectName("pokedex")
        pokedex.resize(591, 561)
        self.centralwidget = QtWidgets.QWidget(pokedex)
        self.centralwidget.setObjectName("centralwidget")
        self.FramePrincipal = QtWidgets.QFrame(self.centralwidget)
        self.FramePrincipal.setGeometry(QtCore.QRect(0, 0, 591, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FramePrincipal.sizePolicy().hasHeightForWidth())
        self.FramePrincipal.setSizePolicy(sizePolicy)
        self.FramePrincipal.setAutoFillBackground(False)
        self.FramePrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FramePrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FramePrincipal.setObjectName("FramePrincipal")
        self.LbImagem = QtWidgets.QLabel(self.FramePrincipal)
        self.LbImagem.setGeometry(QtCore.QRect(60, 20, 461, 201))
        self.LbImagem.setStyleSheet("background-color: lightblue\n"
"")
        self.LbImagem.setText("")
        self.LbImagem.setObjectName("LbImagem")
        self.LbTipo1 = QtWidgets.QLabel(self.FramePrincipal)
        self.LbTipo1.setGeometry(QtCore.QRect(30, 260, 171, 41))
        self.LbTipo1.setStyleSheet("background-color: purple\n"
"")
        self.LbTipo1.setText("")
        self.LbTipo1.setObjectName("LbTipo1")
        self.LbTipo2 = QtWidgets.QLabel(self.FramePrincipal)
        self.LbTipo2.setGeometry(QtCore.QRect(30, 310, 171, 41))
        self.LbTipo2.setStyleSheet("background-color: green\n"
"\n"
"")
        self.LbTipo2.setText("")
        self.LbTipo2.setObjectName("LbTipo2")
        self.BtnPrevious = QtWidgets.QPushButton(self.FramePrincipal)
        self.BtnPrevious.setGeometry(QtCore.QRect(260, 310, 131, 41))
        self.BtnPrevious.setObjectName("BtnPrevious")
        self.BtnNext = QtWidgets.QPushButton(self.FramePrincipal)
        self.BtnNext.setGeometry(QtCore.QRect(430, 310, 131, 41))
        self.BtnNext.setObjectName("BtnNext")
        self.BtnAdd = QtWidgets.QPushButton(self.FramePrincipal)
        self.BtnAdd.setGeometry(QtCore.QRect(260, 260, 131, 41))
        self.BtnAdd.setObjectName("BtnAdd")
        self.BtnEdit = QtWidgets.QPushButton(self.FramePrincipal)
        self.BtnEdit.setGeometry(QtCore.QRect(430, 260, 131, 41))
        self.BtnEdit.setObjectName("BtnEdit")
        self.TBDescricao = QtWidgets.QTextBrowser(self.FramePrincipal)
        self.TBDescricao.setGeometry(QtCore.QRect(10, 380, 571, 171))
        self.TBDescricao.setObjectName("TBDescricao")
        pokedex.setCentralWidget(self.centralwidget)

        self.retranslateUi(pokedex)
        QtCore.QMetaObject.connectSlotsByName(pokedex)

    def retranslateUi(self, pokedex):
        _translate = QtCore.QCoreApplication.translate
        pokedex.setWindowTitle(_translate("pokedex", "MainWindow"))
        self.BtnPrevious.setText(_translate("pokedex", "Anterior"))
        self.BtnNext.setText(_translate("pokedex", "Próximo"))
        self.BtnAdd.setText(_translate("pokedex", "Add Poké"))
        self.BtnEdit.setText(_translate("pokedex", "Edit Poké"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pokedex = QtWidgets.QMainWindow()
    ui = Ui_pokedex()
    ui.setupUi(pokedex)
    pokedex.show()
    sys.exit(app.exec_())
